# Generated by Django 5.2.7 on 2025-10-27 02:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idioma', models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('xx', 'Bilingüe')], default='es', max_length=2)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.chofer')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.guia')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.servicio')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pasajero', models.CharField(default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('total_nocontable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('estado', models.CharField(choices=[('0', 'Pagado'), ('1', 'Deuda')], default='1', max_length=1)),
                ('tipo_documento', models.CharField(choices=[('0', 'Boleta'), ('1', 'Factura'), ('2', 'Otros')], default='2', max_length=1)),
                ('tipo_pago', models.CharField(blank=True, choices=[('0', 'Efectivo'), ('1', 'Depósito'), ('2', 'Otro')], max_length=1, null=True)),
                ('girado_cuando', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('cuentas', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('girado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='girado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAdicionalDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cuando', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.adicional')),
                ('pertenece_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pax', models.IntegerField()),
                ('cuando', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('seleccionado', models.BooleanField(default=False)),
                ('idioma', models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('xx', 'Bilingüe')], default='es', max_length=2)),
                ('pertenece_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva')),
                ('recoger_en', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.lugar')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('pertenece_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.ordenservicio')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reservadetalle')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
