# Generated by Django 5.2.7 on 2025-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='idioma',
            field=models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('xx', 'Bilingüe')], max_length=2),
        ),
    ]
