# Generated by Django 5.2.7 on 2025-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_ordenservicio_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadetalle',
            name='destino',
            field=models.CharField(blank=True, help_text='Destino final del servicio si el servicio lo requiere', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='observacion_precio',
            field=models.CharField(blank=True, help_text='Observación sobre el precio aplicado (ej: "Precio especial para agencia X")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario que se aplicó (puede ser precio especial)', max_digits=11, null=True),
        ),
    ]
