# Generated by Django 5.2.7 on 2025-11-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_responsable'),
        ('reservas', '0003_reservadetalle_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.responsable'),
        ),
    ]
