# Generated by Django 5.2.7 on 2026-02-28 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_ordenservicio_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaadicionaldetalle',
            name='pertenece_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='reservadetalle',
            name='pertenece_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
    ]
