# Generated by Django 5.2.7 on 2026-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_cambiar_cascade_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadetalle',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del servicio para esta reserva', null=True),
        ),
    ]
