# Generated by Django 5.2.7 on 2026-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reservadetalle_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaadicionaldetalle',
            name='observacion_precio',
            field=models.CharField(blank=True, help_text='Observación sobre el precio aplicado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservaadicionaldetalle',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario que se aplicó (puede ser precio especial)', max_digits=11, null=True),
        ),
    ]
