# Generated by Django 5.2.7 on 2025-11-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mostrar_destinos',
            field=models.BooleanField(default=False, help_text='Si está activo, al agregar este servicio en una reserva se solicitará un destino'),
        ),
        migrations.CreateModel(
            name='ServicioParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la parada', max_length=255)),
                ('orden', models.IntegerField(default=0, help_text='Orden en el itinerario')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la parada', null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='base.servicio')),
            ],
            options={
                'verbose_name': 'Parada de Servicio',
                'verbose_name_plural': 'Paradas de Servicios',
                'ordering': ['servicio', 'orden'],
                'unique_together': {('servicio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ServicioPrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio especial para esta agencia', max_digits=11)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField(help_text='Fecha desde la cual aplica este precio')),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual aplica (opcional)', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='base.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='base.servicio')),
            ],
            options={
                'verbose_name': 'Precio Especial de Servicio',
                'verbose_name_plural': 'Precios Especiales de Servicios',
                'ordering': ['-fecha_desde'],
                'unique_together': {('servicio', 'cliente')},
            },
        ),
    ]
