# Generated by Django 5.2.7 on 2025-11-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cantidad_carrito',
        ),
        migrations.DeleteModel(
            name='Formato',
        ),
    ]
