# Generated by Django 5.2.7 on 2026-02-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_formato_and_cantidad_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalPrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio especial para esta agencia', max_digits=11)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField(help_text='Fecha desde la cual aplica este precio')),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual aplica (opcional)', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='base.adicional')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales_precios_especiales', to='base.cliente')),
            ],
            options={
                'verbose_name': 'Precio Especial de Adicional',
                'verbose_name_plural': 'Precios Especiales de Adicionales',
                'ordering': ['-fecha_desde'],
                'unique_together': {('adicional', 'cliente')},
            },
        ),
    ]
