# Generated by Django 5.2.7 on 2026-02-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adicional_precio_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
