# Generated by Django 5.2.7 on 2026-04-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cambiar_object_id_bigint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicioColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('pax', 'PAX'), ('hotel', 'Hotel / Recojo'), ('pasajero', 'Pasajero'), ('agencia', 'Agencia'), ('destino', 'Destino'), ('ingresos', 'Ingresos / Boletos'), ('almuerzo', 'Almuerzo'), ('adicionales', 'Adicionales'), ('observaciones', 'Observaciones')], max_length=20)),
                ('etiqueta', models.CharField(help_text='Texto del encabezado de la columna en el PDF', max_length=60)),
                ('ancho', models.IntegerField(default=10, help_text='Ancho aproximado en % del total de la tabla')),
                ('orden', models.IntegerField(default=0, help_text='Posición de la columna (0 = más a la izquierda)')),
                ('visible', models.BooleanField(default=True, help_text='Si False, la columna no aparece en el PDF')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas_orden', to='base.servicio')),
            ],
            options={
                'verbose_name': 'Columna de Orden de Servicio',
                'verbose_name_plural': 'Columnas de Orden de Servicio',
                'ordering': ['orden'],
                'unique_together': {('servicio', 'clave')},
            },
        ),
    ]
